### ISSUE TITLE
Start Direct Migration while Initial Backup runs

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-controller#1039]
Start the DVM closer to the beginning of MigMigration while the initial backup runs (being sure to annotate rsync resources with `velero.io/excluded-from-backup`), and have the Rsync and Stunnel Pods be "running" but idle until the signal is given to actually start the rsync?.

This would also move the DVM to the "Backup" phase instead of the "StageBackup" phase.

**Comment by sseago** [comment]
Wouldn't this run into problems with quiesce? We'd want to quiesce pods before starting DVM, but we *can't* quiesce pods until the initial backup has completed.

**Comment by djwhatle** [comment]
@sseago my thought was to have the Rsync Pods running but not moving any data until quiesce is completed. This may not be feasible due to PVC access rules. Thoughts?

**Comment by sseago** [comment]
@djwhatle So the issue is that certain combinations of access mode and storage plugin may not let the pod mount the pods until quiesce is completed. This would be fine with EBS RWO volumes, but probably not with ROKS RWO volumes. WIth ebs, two pods can mount a single RWO volume as long as they're on the same node. With ROKS, they can't do this, which would mean that any pods on the src cluster that will be mounting the copy volumes couldn't be mounted if the application pod is still using it.

**Comment by djwhatle** [comment]
After vetting this idea with the team, it seems infeasible or at least not worth the performance improvement we could get from it.
