### ISSUE TITLE
Add ability to cancel a Stage/Migrate in process

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-controller#237]

**Comment by Danil-Grigorev** [comment]
@jortel @djwhatle After yesterday's discussion with Jeff, the initial approach could look like this.

**Comment by vconzola** [comment]
@Danil-Grigorev I'm looking at the UI needs for cancelling a migration. https://github.com/konveyor/mig-ui/issues/425 I'm trying to figure out what your PR https://github.com/konveyor/mig-controller/pull/452 does exactly. Does this PR cancel a stage/migrate in process, but leave the plan "open" so it can be staged/migrated again later? Or does it cancel the whole plan and move the plan into a "completed" state?

**Comment by Danil-Grigorev** [comment]
@vconzola There is a demo showcasing the functionality. [demo]()

Controller will never `close` a plan, unless it is told to do so. The UI does this instead, so in order to integreate the feature into ui, in addition to steps you described in https://github.com/konveyor/mig-ui/issues/425#issuecomment-604021077 it is necessary to prevent the `MigPlan` from being automatically cancelled, same as for the stage migration (cc @eriknelson @ibolton336)

**Comment by vconzola** [comment]
@Danil-Grigorev Mockups are here: https://docs.google.com/presentation/d/1Fv8pUuAl48umIjJKEkyw1TUWR_IfMp5w8HuZXe4-l9c/edit?usp=sharing
Let me know if you have any questions.
