### ISSUE TITLE
(bug): Controller error during pv discovery

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-controller#440]
When attempting PV discovery, I am seeing the UI hang. Looked at the pod list & the controller was entering into a crash loop. Other useful info that may help in debugging: I am running the UI on my 4 cluster, but I am attempting to create a migplan to migrate a 3 cluster to a separate 4 cluster (not the host cluster I am running the UI from). 

```
/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x13717fe]

goroutine 265 [running]:
github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/konveyor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x18edfa0, 0x2b24940)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/konveyor/mig-controller/pkg/apis/migration/v1alpha1.(*MigCluster).BuildRestConfig(0xc42359cea0, 0x1d50a60, 0xc42487c000, 0x1d50a60, 0xc42487c000, 0x0)
	/go/src/github.com/konveyor/mig-controller/pkg/apis/migration/v1alpha1/migcluster_types.go:164 +0x12e

```

**Comment by sseago** [comment]
Looking into the underlying issue here, there are two intersecting problems:
1) BuildRestConfig doesn't check for a nil secret return (GetSecret returns nil, nil if the secret isn't found but there are no other errors), which is the immediate cause of the nil pointer dereference
2) Sometimes the cached (local) client fails to find secrets. It's not a race condition -- when this occurs, in a given environment, it will consistently fail to find secrets no matter how much time has passed. As a temporary workaround I was able to get past this by modifying GetSecret to create its own non-cached client when the normal client failed. This confirmed that the cached client was the source of the problem. A more appropriate short-term fix would be to disable the cached client completely for the local cluster (as we're already doing for remote clusters). Longer-term, we should probably figure out why the cached client is failing to find secrets (but no issues with other resources).

**Comment by ibolton336** [comment]
Steps to reproduce:
via ui:
1) add 3 cluster (insecure)
2) add additional 4 cluster (non-host) (insecure)
3) create migplan, select namespace with RWX PV
4) initiate PV discovery

**Comment by ibolton336** [comment]
![image](https://user-images.githubusercontent.com/11218376/75911042-e6a6ae80-5e1c-11ea-87dc-8c379e49a70b.png)

**Comment by ibolton336** [comment]
![controller-bug-ui-gif](https://user-images.githubusercontent.com/11218376/75911501-aa278280-5e1d-11ea-94b1-8e339086455d.gif)
