### ISSUE TITLE
Migration fails without any error

### ISSUE THREAD

**Issue by jmontleon** [konveyor/mig-controller#514]
@ashwinlohia filed an issue under mig-operator about a failed migration that reported success. Since the installation succeeded I think this is down to controller/velero so moving here for better visibility

Original is at: https://github.com/konveyor/mig-operator/issues/300

I tried to do a migration from OCP 3.11 to 4.3 but it doesn't complete. All checks however look fine.

From velero logs,
time="2020-04-15T11:24:18Z" level=info msg="Syncing contents of backup store into cluster" backupLocation=migstorage-sample-986wl controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:176"
time="2020-04-15T11:24:18Z" level=info msg="Got backups from backup store" backupCount=0 backupLocation=migstorage-sample-986wl controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:184"

Migration status -

Conditions:
Category: Advisory
Durable: true
Last Transition Time: 2020-04-15T11:12:53Z
Message: The migration has completed successfully.
Reason: Completed
Status: True
Type: Succeeded
Phase: Completed
Start Timestamp: 2020-04-15T11:12:43Z
Events:

**Comment by sseago** [comment]
From the logs the migmigration status, the migration did complete. Where are you seeing a failure?

Is it possible that you did a stage migration but didn't have any PVs to copy? The stage migration only copies persistent volumes (it will eventually include internal images as well), so if you do a stage migration on a stateless namespace, there aren't actually any velero actions to be triggered. We've recently introduced a warning condition added to the migmigration for cases like this since we had a similar bug report issued for a no-op stage migration. The warning will make it clear that nothing failed, but that there were no velero actions necessary.

**Comment by sseago** [comment]
The related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1824395
The related PR: https://github.com/konveyor/mig-controller/pull/510

**Comment by djwhatle** [comment]
Resolved by #510
