### ISSUE TITLE
Clarify exactly what the "Phase" means?

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-controller#615]
It's not clear what the "phase" actually represents. Trying to be specific,
is this the "last started phase", and when an error occurs, the phase is simply
left alone? So is it fair to say the phase seen here really is the "failed" phase?
Is there anything that can be done here to help? There is some perception that this
is the last successfully completed phase, but not the **failed** phase, and that
can lead to a misleading debug experience. I'm not sure that there's something
that needs to change here, but would like some clarity on the topic so we can
be accurate with our debug guide language.

**Comment by djwhatle** [comment]
Hey Erik,

The `Phase` you see reflected on the `MigMigration` object reflects _our current step in a series of migration actions_  to be performed.

> is this the "last started phase", and when an error occurs, the phase is simply left alone?
 
If we're able to notice a failure we will switch over to the `FailedItinerary`, which has its own set of phases to run through. We normally won't leave a `Phase` alone unless we are at a terminal state or are otherwise unable to detect any change in the system that would prompt progression in a migration.

>There is some perception that this is the last successfully completed phase

I'm not sure where this perception came from, but this is not my understanding of Phase, see above. The `Phase` you see in status is where we are right now.






```
var FinalItinerary = Itinerary{
	Name: "Final",
	Steps: []Step{
		{phase: Created},
		{phase: Started},
		{phase: Prepare},
		{phase: EnsureCloudSecretPropagated},
		{phase: PreBackupHooks},
		{phase: EnsureInitialBackup},
		{phase: InitialBackupCreated},
		{phase: EnsureStagePodsFromRunning, all: HasPVs},
		{phase: EnsureStagePodsFromTemplates, all: HasPVs},
		{phase: EnsureStagePodsFromOrphanedPVCs, all: HasPVs},
		{phase: StagePodsCreated, all: HasStagePods},
		{phase: AnnotateResources, all: HasPVs},
		{phase: RestartRestic, all: HasStagePods},
		{phase: ResticRestarted, all: HasStagePods},
		{phase: QuiesceApplications, all: Quiesce},
		{phase: EnsureQuiesced, all: Quiesce},
		{phase: EnsureStageBackup, all: HasPVs},
		{phase: StageBackupCreated, all: HasPVs},
		{phase: EnsureStageBackupReplicated, all: HasPVs},
		{phase: EnsureStageRestore, all: HasPVs},
		{phase: StageRestoreCreated, all: HasPVs},
		{phase: EnsureStagePodsDeleted, all: HasStagePods},
		{phase: EnsureStagePodsTerminated, all: HasStagePods},
		{phase: EnsureAnnotationsDeleted, all: HasPVs},
		{phase: EnsureInitialBackupReplicated},
		{phase: PostBackupHooks},
		{phase: PreRestoreHooks},
		{phase: EnsureFinalRestore},
		{phase: FinalRestoreCreated},
		{phase: EnsureLabelsDeleted},
		{phase: PostRestoreHooks},
		{phase: Verification, all: HasVerify},
		{phase: Completed},
	},
}

var CancelItinerary = Itinerary{
	Name: "Cancel",
	Steps: []Step{
		{phase: Canceling},
		{phase: DeleteBackups},
		{phase: DeleteRestores},
		{phase: EnsureStagePodsDeleted, all: HasStagePods},
		{phase: EnsureAnnotationsDeleted, all: HasPVs},
		{phase: DeleteMigrated},
		{phase: EnsureMigratedDeleted},
		{phase: UnQuiesceApplications, all: Quiesce},
		{phase: Canceled},
		{phase: Completed},
	},
}

var FailedItinerary = Itinerary{
	Name: "Failed",
	Steps: []Step{
		{phase: MigrationFailed},
		{phase: EnsureStagePodsDeleted, all: HasStagePods},
		{phase: EnsureAnnotationsDeleted, all: HasPVs},
		{phase: DeleteMigrated},
		{phase: EnsureMigratedDeleted},
		{phase: UnQuiesceApplications, all: Quiesce},
		{phase: Completed},
	},
}
```

**Itineraries (set of stages to be run):**
 - [StageItinerary](https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migmigration/task.go#L120-L157)
 - [FinalItinerary](https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migmigration/task.go#L120-L157)
 - [CancelItinerary](https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migmigration/task.go#L159-L173)
 - [FailedItinerary](https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migmigration/task.go#L175-L186)

**Comment by eriknelson** [comment]
CC @jwmatthews Do we have a specific example where something has failed and the phase was confusing users? I recall from our conversations this specific issue being called out, but as @djwhatle points out here, it's *not* the last successful phase.

Anecdotally, I think I've seen migrations never enter the failed itinerary, but I'm curious what John has to say in response to this.

**Comment by djwhatle** [comment]
@eriknelson @jwmatthews any further clarification or action needed here?

**Comment by eriknelson** [comment]
I'd like to leave this open so I can provide a specific example of the
issue once it arises, if it arises. I'll timebox it by the 1.3 release,
otherwise I'll close this.

**Comment by djwhatle** [comment]
@eriknelson I'm doing a thorough review of phase names right now (and adding detailed descriptions for each phase), and I think I see what may be causing some of the confusion. Some of our phases don't describe what is currently happening at all, they're just poorly named.

I'll attempt fixing this and reply back here with a link to the PR.

**Comment by djwhatle** [comment]
@eriknelson I'm starting on improvements to phase details now. 

**Part 1:** more detailed phase info in status: https://github.com/konveyor/mig-controller/pull/656
**Part 2:** rename phases to align better with their actual jobs

**Comment by djwhatle** [comment]
Work is being tracked in the above two issues. Closing.
